# Generated by Django 5.0.3 on 2024-03-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_category_drinks_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinks',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
